name: Build Android APK

on:
  push:
    branches:
      - main
      - dev
      - new-features
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Setup environment variables
        run: |
          echo "EXPO_PUBLIC_MAPBOX_PUBLIC_TOKEN=${{ secrets.MAPBOX_PUBLIC_TOKEN }}" >> .env
          echo "MAPBOX_DOWNLOAD_TOKEN=${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}" >> .env
          echo "EXPO_PUBLIC_EAS_PROJECT_ID=${{ secrets.EAS_PROJECT_ID }}" >> .env
          echo "EXPO_PUBLIC_ENABLE_MAPBOX=true" >> .env

      - name: Extract version from app.json
        id: version
        run: |
          VERSION=$(node -p "require('./app.json').expo.version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Build Android APK
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/pars-en-cours-v${{ steps.version.outputs.version }}-preview.apk
        env:
          EXPO_PUBLIC_MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
          MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
          EXPO_PUBLIC_EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
          EXPO_PUBLIC_ENABLE_MAPBOX: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pars-en-cours-v${{ steps.version.outputs.version }}-preview-${{ github.sha }}
          path: ${{ github.workspace }}/pars-en-cours-v${{ steps.version.outputs.version }}-preview.apk
          retention-days: 30

