name: Validate Translations

on:
  push:
    paths:
      - 'src/i18n/locales/**'
      - 'src/i18n/**'
  pull_request:
    paths:
      - 'src/i18n/locales/**'
      - 'src/i18n/**'

jobs:
  validate-translations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate translations
        run: npm run validate-translations
        
      - name: Comment PR with validation results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              const output = execSync('npm run validate-translations', { encoding: 'utf8' });
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## Translation Validation Results ✅\n\n\`\`\`\n${output}\n\`\`\`\n\nAll translations are valid!`
              });
            } catch (error) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## Translation Validation Results ❌\n\n\`\`\`\n${error.stdout || error.message}\n\`\`\`\n\nPlease fix the translation issues before merging.`
              });
            }
